#!/bin/sh
set -eu

mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS ${EJ1_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ${EJ2_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON ${EJ1_DB_NAME}.* TO '${MARIADB_USER}'@'%';
GRANT ALL PRIVILEGES ON ${EJ2_DB_NAME}.* TO '${MARIADB_USER}'@'%';

FLUSH PRIVILEGES;
SQL
